# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager"
  homepage "https://github.com/default-anton/wt"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/default-anton/wt/releases/download/v0.3.3/wt_0.3.3_darwin_amd64.tar.gz"
      sha256 "12c20afab502f6b64dd9a40e61adf6920f8c15b16d78a8431e57802fae67f03a"

      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/default-anton/wt/releases/download/v0.3.3/wt_0.3.3_darwin_arm64.tar.gz"
      sha256 "45c71dc5b25cbfa0b689f930fac5ea69ac8c42b1700e2ba219c417193eb85bc7"

      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/default-anton/wt/releases/download/v0.3.3/wt_0.3.3_linux_amd64.tar.gz"
      sha256 "88b854efa31385305580e55a789b4a0e4b3fc84aa32b53c9c92e491c2149f8be"
      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/default-anton/wt/releases/download/v0.3.3/wt_0.3.3_linux_arm64.tar.gz"
      sha256 "da2bfa8f5c022fa381e1ab5a1f930dab9397a0d94edb2993161a534bedfe5b13"
      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
  end
end
