# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager"
  homepage "https://github.com/default-anton/wt"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/default-anton/wt/releases/download/v0.3.2/wt_0.3.2_darwin_amd64.tar.gz"
      sha256 "c35557c50e19872a55045bbb7557b0fde94339afb2635c7cffc98b00390bda5c"

      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/default-anton/wt/releases/download/v0.3.2/wt_0.3.2_darwin_arm64.tar.gz"
      sha256 "1e6074949a85b6cf5f2871841a36d3a5855b1069a7ac980873d9a291517c3746"

      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/default-anton/wt/releases/download/v0.3.2/wt_0.3.2_linux_amd64.tar.gz"
      sha256 "cf0731b492e72508520f1e79fb8f1fb468c83fb3443fb6f381f652971f927189"
      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/default-anton/wt/releases/download/v0.3.2/wt_0.3.2_linux_arm64.tar.gz"
      sha256 "a97a04d12111b136f655b403197eedf07bd5514932e45eb0e251a6d2cbc625e1"
      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
  end
end
