# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager"
  homepage "https://github.com/default-anton/wt"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/default-anton/wt/releases/download/v0.3.4/wt_0.3.4_darwin_amd64.tar.gz"
      sha256 "2ef28c03a653874859b295102927994654acb8d173d65710543dee1b9a0b71b1"

      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/default-anton/wt/releases/download/v0.3.4/wt_0.3.4_darwin_arm64.tar.gz"
      sha256 "67aa357d02bfdb562c4dc47f5fcf8afdb2a71090a78160b92cdaf49af5d0effe"

      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/default-anton/wt/releases/download/v0.3.4/wt_0.3.4_linux_amd64.tar.gz"
      sha256 "bfa2d6e56314827581767e7926cdd50fc363b743a34f7ec346751964303521cb"
      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/default-anton/wt/releases/download/v0.3.4/wt_0.3.4_linux_arm64.tar.gz"
      sha256 "97a30fc23a9b34436bbd730e7d152648ca5fc82a37959a2aeef4a854f06c77b5"
      def install
        bin.install "wt"

        # Install shell-init (wrapper function) + completions combined
        (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
        (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
        (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
      end
    end
  end
end
